# Generated by Django 4.2.29 on 2026-05-29 05:29

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('fecha_creacion', models.DateField(blank=True, null=True)),
                ('nombre_entrenador', models.CharField(max_length=100)),
                ('nombre_dueno', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Jugador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('rut', models.CharField(max_length=12, unique=True)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('contacto_emergencia', models.CharField(blank=True, max_length=20, null=True)),
                ('fecha_inscripcion', models.DateField(default=django.utils.timezone.now)),
                ('adulto_responsable', models.CharField(blank=True, max_length=200, null=True)),
                ('tipo_sangre', models.CharField(blank=True, max_length=5, null=True)),
                ('tiene_seguro', models.BooleanField(default=False)),
                ('alergias', models.TextField(blank=True, null=True)),
                ('certificado_medico', models.FileField(blank=True, null=True, upload_to='certificados/')),
                ('activo', models.BooleanField(default=True)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jugadores', to='myapp.equipo')),
            ],
        ),
        migrations.CreateModel(
            name='Liga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('fecha_fundacion', models.DateField(blank=True, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='ligas/logos/')),
                ('comuna', models.CharField(default='Osorno', max_length=100)),
                ('region', models.CharField(default='Los Lagos', max_length=100)),
                ('direccion', models.CharField(blank=True, max_length=100, null=True)),
                ('presidente', models.CharField(blank=True, max_length=100, null=True)),
                ('secretario', models.CharField(blank=True, max_length=100, null=True)),
                ('tesorero', models.CharField(blank=True, max_length=100, null=True)),
                ('telefono_contacto', models.CharField(blank=True, max_length=20, null=True)),
                ('correo_contacto', models.EmailField(blank=True, max_length=254, null=True)),
                ('redes_sociales', models.CharField(max_length=100)),
                ('reglamento', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Traspaso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inscripcion_anterior', models.DateField()),
                ('fecha_inscripcion_actual', models.DateField(default=django.utils.timezone.now)),
                ('equipo_destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='traspasos_entrada', to='myapp.equipo')),
                ('equipo_origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='traspasos_salida', to='myapp.equipo')),
                ('jugador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='traspasos', to='myapp.jugador')),
            ],
        ),
        migrations.AddField(
            model_name='equipo',
            name='liga',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.liga'),
        ),
        migrations.CreateModel(
            name='Dirigente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('rut', models.CharField(max_length=12, unique=True)),
                ('telefono', models.CharField(max_length=20)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('cargo', models.CharField(max_length=50)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha_asuncion', models.DateField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dirigentes', to='myapp.equipo')),
            ],
        ),
    ]
