# Generated by Django 4.2.29 on 2026-06-26 02:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('myapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dirigente',
            name='usuario',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='redsocial',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('equipo__isnull', False), ('liga__isnull', True)), models.Q(('equipo__isnull', True), ('liga__isnull', False)), _connector='OR'), name='red_social_tiene_un_propietario'),
        ),
        migrations.AddConstraint(
            model_name='redsocial',
            constraint=models.UniqueConstraint(fields=('equipo', 'tipo', 'enlace'), name='red_social_unica_por_equipo'),
        ),
        migrations.AddConstraint(
            model_name='redsocial',
            constraint=models.UniqueConstraint(fields=('liga', 'tipo', 'enlace'), name='red_social_unica_por_liga'),
        ),
    ]
