# Generated by Django 4.2.29 on 2026-04-29 03:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='traspaso',
            old_name='fecha',
            new_name='fecha_inscripcion_actual',
        ),
        migrations.AddField(
            model_name='traspaso',
            name='fecha_inscripcion_anterior',
            field=models.DateField(default=datetime.date(2024, 4, 28)),
            preserve_default=False,
        ),
    ]
