# Generated by Django 4.2.29 on 2026-06-26 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='arbitro',
            name='alergias',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='arbitro',
            name='certificado_medico',
            field=models.FileField(blank=True, null=True, upload_to='certificados_arbitros/'),
        ),
        migrations.AddField(
            model_name='arbitro',
            name='contacto_emergencia',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='arbitro',
            name='tiene_seguro',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='arbitro',
            name='tipo_sangre',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
