# Generated by Django 4.2.29 on 2026-05-29 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='redes_sociales',
            field=models.CharField(default='sin-redes', max_length=100),
            preserve_default=False,
        ),
    ]
