# Generated by Django 4.2.29 on 2026-04-09 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_liga'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='liga',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.liga'),
        ),
    ]
