# Generated by Django 4.2.29 on 2026-05-07 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_fecha_traspaso_fecha_inscripcion_actual_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jugador',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
