# Generated by Django 4.2.29 on 2026-04-11 04:44

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_equipo_liga'),
    ]

    operations = [
        migrations.AddField(
            model_name='jugador',
            name='fecha_inscripcion',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='jugador',
            name='equipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jugadores', to='myapp.equipo'),
        ),
        migrations.CreateModel(
            name='Traspaso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('equipo_destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='traspasos_entrada', to='myapp.equipo')),
                ('equipo_origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='traspasos_salida', to='myapp.equipo')),
                ('jugador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='traspasos', to='myapp.jugador')),
            ],
        ),
    ]
