# Generated by Django 4.2.29 on 2026-06-26 03:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_arbitro_alergias_arbitro_certificado_medico_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cancha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='canchas/')),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('tipo_superficie', models.CharField(choices=[('NATURAL', 'Pasto Natural'), ('SINTETICA', 'Pasto Sintético'), ('TIERRA', 'Tierra')], default='NATURAL', max_length=20)),
                ('capacidad', models.PositiveIntegerField(blank=True, null=True)),
                ('iluminacion', models.BooleanField(default=False)),
                ('activa', models.BooleanField(default=True)),
                ('liga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='canchas', to='myapp.liga')),
            ],
        ),
    ]
