# Generated by Django 4.2.29 on 2026-06-26 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_cancha'),
    ]

    operations = [
        migrations.AddField(
            model_name='cancha',
            name='mapa_iframe',
            field=models.TextField(blank=True, null=True, verbose_name='Código HTML del mapa'),
        ),
    ]
