# Generated by Django 4.2.29 on 2026-05-26 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_dirigente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dirigente',
            name='activo',
        ),
    ]
