# Generated by Django 4.2.29 on 2026-04-11 04:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_jugador_fecha_inscripcion_alter_jugador_equipo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jugador',
            name='fecha_inscripcion',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
