# Generated by Django 4.2.29 on 2026-06-26 03:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_cancha_mapa_iframe'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('goles_local', models.PositiveIntegerField(blank=True, null=True)),
                ('goles_visitante', models.PositiveIntegerField(blank=True, null=True)),
                ('descripcion', models.TextField(blank=True)),
                ('amarillas_local', models.PositiveIntegerField(default=0)),
                ('amarillas_visitante', models.PositiveIntegerField(default=0)),
                ('rojas_local', models.PositiveIntegerField(default=0)),
                ('rojas_visitante', models.PositiveIntegerField(default=0)),
                ('cancha', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partidos', to='myapp.cancha')),
                ('equipo_local', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidos_local', to='myapp.equipo')),
                ('equipo_visitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidos_visitante', to='myapp.equipo')),
            ],
        ),
    ]
