# Generated by Django 4.2.29 on 2026-06-26 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_partido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arbitro',
            name='estado',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='arbitro',
            name='experiencia',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='arbitro',
            name='rut',
            field=models.CharField(max_length=12, unique=True),
        ),
    ]
