# Generated by Django 4.2.29 on 2026-07-10 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_arbitro_estado_alter_arbitro_experiencia_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cancha',
            name='capacidad',
        ),
        migrations.RemoveField(
            model_name='cancha',
            name='mapa_iframe',
        ),
        migrations.AddField(
            model_name='cancha',
            name='ancho_metros',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Ancho de la cancha (m)'),
        ),
        migrations.AddField(
            model_name='cancha',
            name='capacidad_maxima',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Capacidad máxima de espectadores'),
        ),
        migrations.AddField(
            model_name='cancha',
            name='capacidad_minima',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Capacidad mínima de espectadores'),
        ),
        migrations.AddField(
            model_name='cancha',
            name='largo_metros',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Largo de la cancha (m)'),
        ),
        migrations.AddField(
            model_name='cancha',
            name='latitud',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitud'),
        ),
        migrations.AddField(
            model_name='cancha',
            name='longitud',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitud'),
        ),
    ]
