# Generated by Django 4.2.29 on 2026-07-10 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_remove_cancha_capacidad_remove_cancha_mapa_iframe_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partido',
            name='amarillas_local',
        ),
        migrations.RemoveField(
            model_name='partido',
            name='amarillas_visitante',
        ),
        migrations.RemoveField(
            model_name='partido',
            name='rojas_local',
        ),
        migrations.RemoveField(
            model_name='partido',
            name='rojas_visitante',
        ),
        migrations.CreateModel(
            name='TarjetaPartido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_tarjeta', models.CharField(choices=[('amarilla', 'Amarilla'), ('roja', 'Roja')], max_length=10)),
                ('afectado', models.CharField(choices=[('campo', 'Jugador en cancha'), ('banca', 'Jugador en banca'), ('tecnico', 'Cuerpo técnico')], max_length=10)),
                ('numero_camiseta', models.PositiveIntegerField(blank=True, null=True)),
                ('nombre_persona', models.CharField(blank=True, max_length=100)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.equipo')),
                ('partido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarjetas', to='myapp.partido')),
            ],
        ),
    ]
