# Generated by Django 4.2.29 on 2026-07-10 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_remove_partido_amarillas_local_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarjetapartido',
            name='afectado',
            field=models.CharField(choices=[('campo', 'Jugador en cancha'), ('banca', 'Jugador en banca'), ('tecnico', 'Cuerpo técnico')], max_length=15),
        ),
    ]
