# Generated by Django 4.2.29 on 2026-08-05 22:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_alter_tarjetapartido_afectado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Torneo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('equipos', models.ManyToManyField(related_name='torneos', to='myapp.equipo')),
            ],
            options={
                'ordering': ['-fecha_inicio', 'nombre'],
            },
        ),
        migrations.AddField(
            model_name='partido',
            name='torneo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='partidos', to='myapp.torneo'),
        ),
    ]
