# Generated by Codex on 2026-08-06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_torneo_partido_torneo'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='equipos/logos/'),
        ),
    ]
