# Generated by Django 4.2.29 on 2026-08-06 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_equipo_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arbitro',
            name='apellido',
        ),
    ]
