# Generated by Django 4.2.29 on 2026-08-07 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_remove_arbitro_apellido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='nombre_dueno',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='nombre_entrenador',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
