# Generated by Django 4.2.29 on 2026-08-11 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_alter_equipo_nombre_dueno_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liga',
            name='nombre',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
