# Generated by Django 4.2.29 on 2026-08-25 04:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_alter_liga_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partido',
            name='torneo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='partidos', to='myapp.torneo'),
        ),
        migrations.CreateModel(
            name='GolPartido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minuto', models.PositiveIntegerField(blank=True, null=True)),
                ('autogol', models.BooleanField(default=False)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goles_marcados', to='myapp.equipo')),
                ('jugador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='goles', to='myapp.jugador')),
                ('partido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goles', to='myapp.partido')),
            ],
        ),
    ]
