# Generated by Django 4.2.29 on 2026-08-25 05:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_alter_partido_torneo_golpartido'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarjetapartido',
            name='afectado',
        ),
        migrations.RemoveField(
            model_name='tarjetapartido',
            name='equipo',
        ),
        migrations.RemoveField(
            model_name='tarjetapartido',
            name='nombre_persona',
        ),
        migrations.RemoveField(
            model_name='tarjetapartido',
            name='numero_camiseta',
        ),
        migrations.AddField(
            model_name='tarjetapartido',
            name='jugador',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tarjetas', to='myapp.jugador'),
            preserve_default=False,
        ),
    ]
