# Generated by Django 4.2.29 on 2026-08-27 03:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0017_remove_tarjetapartido_afectado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarjetapartido',
            name='equipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tarjetas_partido', to='myapp.equipo'),
        ),
        migrations.AlterField(
            model_name='dirigente',
            name='correo',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='dirigente',
            name='rut',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='dirigente',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dirigencias', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tarjetapartido',
            name='jugador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarjetas', to='myapp.jugador'),
        ),
        migrations.AlterField(
            model_name='tarjetapartido',
            name='tipo_tarjeta',
            field=models.CharField(choices=[('amarilla', 'Amarilla'), ('roja', 'Roja')], max_length=20),
        ),
    ]
