# Generated by Django 4.2.29 on 2026-09-23 18:50

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_tarjetapartido_equipo_alter_dirigente_correo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_prestamo', models.DateField(default=django.utils.timezone.now)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('activo', models.BooleanField(default=True)),
                ('equipo_destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prestamos_entrada', to='myapp.equipo')),
                ('equipo_origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prestamos_salida', to='myapp.equipo')),
                ('jugador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prestamos', to='myapp.jugador')),
                ('torneo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prestamos', to='myapp.torneo')),
            ],
        ),
    ]
